### ISSUE TITLE
Unable to build dockerfile with `RUN foundryup` command in dockerfile

### ISSUE THREAD

**Issue by adamdry** [foundry-rs/foundry#2476]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

unknown

### What command(s) is the bug in?

foundryup

### Operating System

Linux

### Describe the bug

When building a docker image with foundry in it the docker build fails with a permissions error on the `foundryup` line. But if I comment this out and then run `foundryup` inside the running container it installs fine. The dockerfile is running (at that point) as the `node` user which is the same user I'm running the command as manually.

Dockerfile:
```docker
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:0-14

# Update all Ubuntu Packages
RUN apt-get update && apt-get upgrade -y

# Install all apt-get packages
RUN apt-get install -y curl \
    python3-pip

# Install node.js
# RUN curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
# RUN apt install -y nodejs

## Install the Hardhat (hh) shortcut tool
RUN npm install -g hardhat-shorthand

#Install rust
USER node
    RUN curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
USER root

#Add Cargo to Path
USER node
    ENV PATH="/root/.cargo/bin:${PATH}"
USER root

# git auto complete
COPY --chown=node:node .git-completion.bash /home/node/.git-completion.bash

# node user's bash setup
COPY --chown=node:node setup-profile.sh /home/node/setup-profile.sh
RUN . /home/node/setup-profile.sh

# install slither
RUN pip3 install slither-analyzer

#Get Foundry
USER node

RUN curl -L https://foundry.paradigm.xyz | bash
CMD /bin/bash -c "source /home/node/.bashrc"
# CMD /bin/bash -c "source /home/root/.bashrc"
RUN foundryup

```

Error from docker build:
```
=> CACHED [10/11] RUN curl -L https://foundry.paradigm.xyz | bash         0.0s
 => ERROR [11/11] RUN foundryup                                            0.5s
------
 > [11/11] RUN foundryup:
#0 0.403 /bin/sh: 1: foundryup: Permission denied
------
error: failed to solve: executor failed running [/bin/sh -c foundryup]: exit code: 127
[2022-07-26T12:28:30.991Z] Stop (870 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /home/adam/adamdryit/customers/thallo/projects/token-vesting-staking-contracts/.devcontainer/Dockerfile -t vsc-token-vesting-staking-contracts-5760759ce41f5cd464a14ec5d4c5f955 --build-arg VARIANT=focal /home/adam/adamdryit/customers/thallo/projects/token-vesting-staking-contracts/.devcontainer
[2022-07-26T12:28:30.992Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /home/adam/adamdryit/customers/thallo/projects/token-vesting-staking-contracts/.devcontainer/Dockerfile -t vsc-token-vesting-staking-contracts-5760759ce41f5cd464a14ec5d4c5f955 --build-arg VARIANT=focal /home/adam/adamdryit/customers/thallo/projects/token-vesting-staking-contracts/.devcontainer
[2022-07-26T12:28:30.993Z]     at GR (/home/adam/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:240:1436)
[2022-07-26T12:28:30.993Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-07-26T12:28:30.993Z]     at async Hu (/home/adam/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:239:2796)
[2022-07-26T12:28:30.993Z]     at async tb (/home/adam/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:239:1779)
[2022-07-26T12:28:30.993Z]     at async QR (/home/adam/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:2006)
[2022-07-26T12:28:30.993Z]     at async cb (/home/adam/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:3110)
[2022-07-26T12:28:30.994Z]     at async i_ (/home/adam/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:13194)
[2022-07-26T12:28:30.994Z]     at async n_ (/home/adam/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:12950)
[2022-07-26T12:28:31.000Z] Stop (1110 ms): Run: /snap/code/102/usr/share/code/code /home/adam/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/adam/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/adam/adamdryit/customers/thallo/projects/token-vesting-staking-contracts --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/adam/adamdryit/customers/thallo/projects/token-vesting-staking-contracts --log-level debug --log-format json --config /home/adam/adamdryit/customers/thallo/projects/token-vesting-staking-contracts/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-07-26T12:28:31.000Z] Exit code 1
[2022-07-26T12:28:31.003Z] Command failed: /snap/code/102/usr/share/code/code /home/adam/.vscode/extensions/ms-vscode-remote.remote-containers-0.241.3/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/adam/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/adam/adamdryit/customers/thallo/projects/token-vesting-staking-contracts --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/adam/adamdryit/customers/thallo/projects/token-vesting-staking-contracts --log-level debug --log-format json --config /home/adam/adamdryit/customers/thallo/projects/token-vesting-staking-contracts/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-07-26T12:28:31.004Z] Exit code 1

```

**Comment by onbjerg** [comment]
I'd assume it is because the file is created as the `node` user which you are not on your own system? In any case, I don't think this is really a Foundry bug since this is your own Docker image, so the error has something to do with Docker

**Comment by Doordashcon** [comment]
Hello @adamdry, where you able to solve this issue?

**Comment by adamdry** [comment]
@Doordashcon no I don't think we did, sorry.

**Comment by Doordashcon** [comment]
Thanks for the response @adamdry, and there are no other solutions you came across for running forge tests with Docker?

**Comment by desi** [comment]
@Doordashcon I was able to get foundryup to run by setting the path variable just before.

Mine looks like this:
```FROM rust:1.67 as builder

SHELL ["/bin/bash", "-c"]

RUN curl -L https://foundry.paradigm.xyz | bash
RUN source ~/.bashrc
ENV PATH="~/.foundry/bin:${PATH}"
RUN foundryup```

Hope it helps.

**Comment by desi** [comment]
So from your error above it seems to me that it doesn't know what shell to use and the path needs to be set. It seems to be using `sh` so try adding

`SHELL ["/bin/sh", "-c"]` after your FROM line. 

And then manually add your env after sourcing the shell file
`RUN source ~/.profile
ENV PATH="~/.foundry/bin:${PATH}"`

I am guessing based on the file you attached and the error message you posted. Hope this helps.

**Comment by r4VP4** [comment]
what solved it for me was adding `RUN chsh -s /bin/bash username` after the `RUN useradd ...`

here is my complete dockerfile
```
FROM ubuntu:22.04 as base_system
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install python3 pip git nano curl iputils-ping redis-tools autossh nmap apt-utils supervisor -y && \
    apt-get clean 

RUN useradd -u 5000 -m appxx
RUN chsh -s /bin/bash appxx

USER appxx:appxx

RUN /bin/bash -c "curl -L https://foundry.paradigm.xyz | bash && /home/appxx/.foundry/bin/foundryup"
```
