### ISSUE TITLE
Anvil unexopecrtedly reverts where hardhat fork & real mainnet not

### ISSUE THREAD

**Issue by 0xmikko** [foundry-rs/foundry#3017]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (307576d 2022-08-29T00:05:05.72678Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Apple Silicon)

### Describe the bug

We're testing Convex integration and found totally unexpected revert in the place, where mainnet and hardhat fork works without any reverts (and it's expected).

How to reproduce:
```typescript=
import { ethers } from "hardhat";
import { waitForTransaction } from "@gearbox-protocol/devops";
import { SignerWithAddress } from "@nomiclabs/hardhat-ethers/signers";
import { BigNumber } from "ethers";

import {
  contractsByNetwork,
  IBaseRewardPool__factory,
  IBooster__factory,
  IERC20Metadata__factory,
  IERC20__factory,
  IUniswapV2Adapter__factory,
  MAX_INT,
  SupportedToken,
  tokenDataByNetwork,
  WAD,
  ICurvePool3Assets__factory,
} from "@gearbox-protocol/sdk";

describe("Convex pool adapter test", async function () {
  this.timeout(0);

  let deployer: SignerWithAddress;
  let user: SignerWithAddress;

  before(async () => {
    const accounts = (await ethers.getSigners()) as Array<SignerWithAddress>;
    deployer = accounts[0];
    user = accounts[1];
  });

  it(`Anvil doesn't work properly`, async function () {
    let booster = IBooster__factory.connect(
      contractsByNetwork.Mainnet.CONVEX_BOOSTER,
      user
    );
    let basePool = IBaseRewardPool__factory.connect(
      contractsByNetwork.Mainnet.CONVEX_3CRV_POOL,
      user
    );

    const curveLPToken = IERC20__factory.connect(
      tokenDataByNetwork.Mainnet["3Crv"],
      deployer
    );

    const pid = await basePool.pid();

    const depositToken = IERC20Metadata__factory.connect(
      tokenDataByNetwork.Mainnet.DAI,
      deployer
    );

    const addressPath = ["WETH", "DAI"].map(
      (symbol) => tokenDataByNetwork.Mainnet[symbol as SupportedToken]
    );

    const uniswapV2 = IUniswapV2Adapter__factory.connect(
      contractsByNetwork.Mainnet.UNISWAP_V2_ROUTER,
      deployer
    );

    console.log("Converting ETH into DAI");

    await waitForTransaction(
      uniswapV2.swapExactETHForTokens(
        0,
        addressPath,
        deployer.address,
        Math.floor(Date.now() / 1000) + 365 * 24 * 3600,
        { value: WAD.mul(10) }
      )
    );

    const amountToDeposit = await depositToken.balanceOf(deployer.address);

    const curvePoolAddress = contractsByNetwork.Mainnet.CURVE_3CRV_POOL;

    console.log("Approving curvePool for DAI");

    await waitForTransaction(depositToken.approve(curvePoolAddress, 0));
    await waitForTransaction(
      depositToken.approve(curvePoolAddress, amountToDeposit)
    );

    const curvePool = ICurvePool3Assets__factory.connect(
      curvePoolAddress,
      deployer
    );

    const amounts = [amountToDeposit, BigNumber.from(0), BigNumber.from(0)] as [
      BigNumber,
      BigNumber,
      BigNumber
    ];

    console.log("Adding liquidity to curvePool");

    await waitForTransaction(curvePool.add_liquidity(amounts, 0));

    const lpTokenBalance = await curveLPToken.balanceOf(deployer.address);

    await waitForTransaction(
      curveLPToken.transfer(user.address, lpTokenBalance)
    );

    console.log("Approving Convex  Booster for 3CRV");

    await waitForTransaction(
      curveLPToken.connect(user).approve(booster.address, 0)
    );

    await waitForTransaction(
      curveLPToken.connect(user).approve(booster.address, MAX_INT)
    );

    let curveLPBalance = await curveLPToken.balanceOf(user.address);

    console.log(`1st call deposit: ${curveLPBalance.toString()}`);
    await waitForTransaction(
      booster.deposit(pid, curveLPBalance.div(2), false)
    );

    const delay = (ms: number) => new Promise((res) => setTimeout(res, ms));

    curveLPBalance = await curveLPToken.balanceOf(user.address);
    console.log(`2nd call deposit: ${curveLPBalance.toString()}`);
    await waitForTransaction(
      booster.deposit(pid, curveLPBalance.div(2), false)
    );
  });
});

```

To get all constants, please run `yarn add @gearbox-protocol/sdk` before running.

Hardhat fork (expected result:
```
  Convex pool adapter test
Converting ETH into DAI
Approving curvePool for DAI
Adding liquidity to curvePool
Approving Convex  Booster for 3CRV
1st call deposit: 91498637493314219025402
2nd call deposit: 45749318746657109512701
    ✔ Anvil doesn't work properly (15165ms)


  1 passing (15s)
  ```
  
  Anvil result:
  ```
  Convex pool adapter test
Converting ETH into DAI
Approving curvePool for DAI
Adding liquidity to curvePool
Approving Convex  Booster for 3CRV
1st call deposit: 15410112781933710237259
2nd call deposit: 7705056390966855118630
    1) Anvil doesn't work properly


  0 passing (18s)
  1 failing

  1) Convex pool adapter test
       Anvil doesn't work properly:
     Error: transaction failed (transactionHash="0x7fcfbd0954941f8f6301371df68d73711dd7e11a2adef57613a994a901e7c4a7", transaction={"hash":"0x7fcfbd0954941f8f6301371df68d73711dd7e11a2adef57613a994a901e7c4a7","type":2,"accessList":[],"blockHash":"0x09efce536ab5c676356161a49a7b4ff0e90e8ee8d4d47d0c9f5fd484ceb904cb","blockNumber":15440130,"transactionIndex":0,"confirmations":1,"from":"0x70997970C51812dc3A010C7d01b50e0d17dc79C8","gasPrice":{"type":"BigNumber","hex":"0x015cfbafcd"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x014886af03"},"gasLimit":{"type":"BigNumber","hex":"0x075833"},"to":"0xF403C135812408BFbE8713b5A23a04b3D48AAE31","value":{"type":"BigNumber","hex":"0x00"},"nonce":39,"data":"0x43a0d06600000000000000000000000000000000000000000000000000000000000000090000000000000000000000000000000000000000000000d0d8919e39165a57930000000000000000000000000000000000000000000000000000000000000000","r":"0x3649bcac42aa0cf0853de56fb73929b9d63d722ae0fbe80304f5cc547d77f954","s":"0x415ea037ae548655620cb738696375f6d4a19d8770585575ddd429a1b843d3cc","v":1,"creates":null,"chainId":1337}, receipt={"to":"0xF403C135812408BFbE8713b5A23a04b3D48AAE31","from":"0x70997970C51812dc3A010C7d01b50e0d17dc79C8","contractAddress":null,"transactionIndex":0,"gasUsed":{"type":"BigNumber","hex":"0x0729ef"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x09efce536ab5c676356161a49a7b4ff0e90e8ee8d4d47d0c9f5fd484ceb904cb","transactionHash":"0x7fcfbd0954941f8f6301371df68d73711dd7e11a2adef57613a994a901e7c4a7","logs":[],"blockNumber":15440130,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x0729ef"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x013d8d7cbd"},"status":0,"type":0,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.4.3)
      at Logger.makeError (node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:213:28)
      at Logger.throwError (node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
      at EthersProviderWrapper.<anonymous> (node_modules/@ethersproject/providers/src.ts/base-provider.ts:1198:24)
      at step (node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
      at Object.next (node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
      at fulfilled (node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      ```

**Comment by 0xmikko** [comment]
Anvil version if needed: anvil 0.1.0 (307576d 2022-08-29T00:05:05.645876Z)

**Comment by DaniPopes** [comment]
Could reproduce on master / latest version, but couldn't on 172d842:

**Comment by 0xmikko** [comment]
It seems, that our mainnet tests work correctly before, we detected the problem yesterday

**Comment by mattsse** [comment]
I fail to debug this locally, because I struggle to make this work.

how do I run this?

**Comment by mattsse** [comment]
maybe related https://github.com/foundry-rs/foundry/pull/3018

**Comment by DaniPopes** [comment]
> I fail to debug this locally, because I struggle to make this work.
> 
> how do I run this?

Created a repo for this: https://github.com/DaniPopes/foundry-3017.git

**Comment by mattsse** [comment]
okay, can reproduce now

tracked it down to ecbd575c2116d8a3aef679d964c3998a838961f7

checking changes now

**Comment by mattsse** [comment]
this looks `timestamp` related,

#2920 made sure the timestamp is always increasing. If I revert this, then it succeeds.

unsure how the timestamp plays a role here with convex, crv

@ngotchac mentioned that hardhat does not always increase, so perhaps we should revert this:

https://github.com/foundry-rs/foundry/blob/a265daa77de0e032e8c66506d0a71026078f83f1/anvil/src/eth/backend/time.rs#L119-L122 

@ngotchac wdyt?

**Comment by ngotchac** [comment]
Okay so I looked a bit, and I think it's more of a gas estimate issue. If you set the gas limit manually to something like 1M it works.

What I think happens is that actually Hardhat estimates gas by default (without block provided) on the pending block; whereas Foundry does so at the latest block. Spec-wise, the latest block is what all other implementations does. But I do see why it could be better to do it on pending block for tests. In any case, as we estimate on Foundry on latest, it uses the last block timestamp, whereas it executes at latest timestamp + 1. So the gas usage might differ when transacting with contracts that uses the block timestamp.

One solution on Foundry's side would be to estimate gas on Pending block if no argument is passed. Otherwise the users will have to use a safer margin when setting gas limit when sending txs. In this, I think it's not that easy since it's all done under the hood by an SDK and not configurable :/

**Comment by 0xmikko** [comment]
It seems more business-logic related, sometimes I got `logs is null` error, and some transactions were mined

**Comment by ngotchac** [comment]
> It seems more business-logic related, sometimes I got `logs is null` error, and some transactions were mined

Where is this check for logs done? Also, have you tried with manually setting the GasLimit field?

**Comment by 0xmikko** [comment]
logs message came from try-catch block in main screen, where at the same time I got `reverted without string` in anvil terminal window
