### ISSUE TITLE
`anvil` fails forking with optimism bedrock release

### ISSUE THREAD

**Issue by dbeal-eth** [foundry-rs/foundry#4094]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b2baca3 2023-01-15T00:04:04.57358143Z)

### What command(s) is the bug in?

anvil --fork-url https://goerli.optimism.io

### Operating System

Linux

### Describe the bug

Optimism has recently completed their optimism bedrock release on goerli. However, forking this network now yields an error in anvil when attempting to do certain RPC calls against the node:

```
code: 'NONCE_EXPIRED',
  error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":49,\"error\":{\"code\":-32603,\"message\":\"Fork Error: JsonRpcClientError(SerdeJson { err: Error(\\\"missing field `v`\\\", line: 1, column: 2201), text: \\\"{\\\\\\\"baseFeePerGas\\\\\\\":\\\\\\\"0x31\\\\\\\",\\\\\\\"difficulty\\\\\\\":\\\\\\\"0x0\\\\\\\",\\\\\\\"extraData\\\\\\\":\\\\\\\"0x\\\\\\\",\\\\\\\"gasLimit\\\\\\\":\\\\\\\"0x17d7840\\\\\\\",\\\\\\\"gasUsed\\\\\\\":\\\\\\\"0x1fee7\\\\\\\",\\\\\\\"hash\\\\\\\":\\\\\\\"0x35861edb0814f1688e949c63729ac877988775396d33c7e3ab8d06f9c2c9543f\\\\\\\",\\\\\\\"logsBloom\\\\\\\":\\\\\\\"0x00000000000000000020000008000000000000000000000000080000000000000000100000000020000000000000000000000000000200000000000000000000000000000000000000000001002000000000000001000000000000000000000000000000020000000000000000000800000000000000000000000000000000000000000000000000000000000000000400000480000000000000000100000000000000001000000000000000000000000000000000000000000000000000000000000000040000000000000000000000004000000000000000000000000820000000000000000000000010000000000000000000000000000000000000000000\\\\\\\",\\\\\\\"miner\\\\\\\":\\\\\\\"0x4200000000000000000000000000000000000011\\\\\\\",\\\\\\\"mixHash\\\\\\\":\\\\\\\"0x1f56f11d6c1f4b6889758ead9d9a6d3e13ae70fdeb524003043eb1d74730d198\\\\\\\",\\\\\\\"nonce\\\\\\\":\\\\\\\"0x0000000000000000\\\\\\\",\\\\\\\"number\\\\\\\":\\\\\\\"0x3f7199\\\\\\\",\\\\\\\"parentHash\\\\\\\":\\\\\\\"0x18095cd3a925b82d8f5581d4017d452197c40b8efa055cc67f393631f59e7cf3\\\\\\\",\\\\\\\"receiptsRoot\\\\\\\":\\\\\\\"0x387bf3d3631899f3879212522e70dc9ec3d2393335529baf20ad12150140b088\\\\\\\",\\\\\\\"sha3Uncles\\\\\\\":\\\\\\\"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347\\\\\\\",\\\\\\\"size\\\\\\\":\\\\\\\"0x663\\\\\\\",\\\\\\\"stateRoot\\\\\\\":\\\\\\\"0x8c44887db7808b97df1c2b708e7a33d15e024eae2f439eb7cc7dd0159ff7c355\\\\\\\",\\\\\\\"timestamp\\\\\\\":\\\\\\\"0x63c34d96\\\\\\\",\\\\\\\"totalDifficulty\\\\\\\":\\\\\\\"0x0\\\\\\\",\\\\\\\"transactions\\\\\\\":[{\\\\\\\"blockHash\\\\\\\":\\\\\\\"0x35861edb0814f1688e949c63729ac877988775396d33c7e3ab8d06f9c2c9543f\\\\\\\",\\\\\\\"blockNumber\\\\\\\":\\\\\\\"0x3f7199\\\\\\\",\\\\\\\"from\\\\\\\":\\\\\\\"0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001\\\\\\\",\\\\\\\"gas\\\\\\\":\\\\\\\"0x8f0d180\\\\\\\",\\\\\\\"hash\\\\\\\":\\\\\\\"0x59010723b292b38c06592588fe571d8eec8bbd866668d5472f8aaf1b1ce041e0\\\\\\\",\\\\\\\"input\\\\\\\":\\\\\\\"0x015d8eb900000000000000000000000000000000000000000000000000000000007ed7eb0000000000000000000000000000000000000000000000000000000063c34d7000000000000000000000000000000000000000000000000000000000372c502ba813d0a707335db70f1fb42a6408bfb12a1308d24e571483512afda1906bca85000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000007431310e026b69bfc676c0013e12a1a11411eec9000000000000000000000000000000000000000000000000000000000000083400000000000000000000000000000000000000000000000000000000000f4240\\\\\\\",\\\\\\\"nonce\\\\\\\":\\\\\\\"0x0\\\\\\\",\\\\\\\"to\\\\\\\":\\\\\\\"0x4200000000000000000000000000000000000015\\\\\\\",\\\\\\\"transactionIndex\\\\\\\":\\\\\\\"0x0\\\\\\\",\\\\\\\"type\\\\\\\":\\\\\\\"0x7e\\\\\\\",\\\\\\\"value\\\\\\\":\\\\\\\"0x0\\\\\\\"},{\\\\\\\"accessList\\\\\\\":[],\\\\\\\"blockHash\\\\\\\":\\\\\\\"0x35861edb0814f1688e949c63729ac877988775396d33c7e3ab8d06f9c2c9543f\\\\\\\",\\\\\\\"blockNumber\\\\\\\":\\\\\\\"0x3f7199\\\\\\\",\\\\\\\"chainId\\\\\\\":\\\\\\\"0x1a4\\\\\\\",\\\\\\\"from\\\\\\\":\\\\\\\"0x48ed4a64892ab8f9a399b92aeb8a97527acdb092\\\\\\\",\\\\\\\"gas\\\\\\\":\\\\\\\"0x7a120\\\\\\\",\\\\\\\"gasPrice\\\\\\\":\\\\\\\"0xb2d05e00\\\\\\\",\\\\\\\"hash\\\\\\\":\\\\\\\"0xd67bfe8f2dc8ced1921384d91693cc9c8682fb2ac3c5cb84aa25f7889cc3c2a0\\\\\\\",\\\\\\\"input\\\\\\\":\\\\\\\"0xc9807539000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000220000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001200000000000000000000000430ba4e77ffb3509e3b9f79077c401a10000027103000102030400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000005000000000000000000000000000000000000000000000000000000000000007d000000000000000000000000000000000000000000000000000000000000007d000000000000000000000000000000000000000000000000000000000000007d000000000000000000000000000000000000000000000000000000000000007d000000000000000000000000000000000000000000000000000000000000007d0000000000000000000000000000000000000000000000000000000000000002a67a46d9aff68582e84544609324fae2d5881e08c6411628932c5d04cb48c217408a890c9ef11d338c4fb7d521e00ba3fd82237ea75809c9d400f4653b3066e000000000000000000000000000000000000000000000000000000000000000025fa9efbb8c704d15c5a591ed462f6f8f16bc86a3df6ed6374e58c63b0b36016f6f87719a1ba9465d9bc6ec7d2e14d1e3ec8550ef4598f1937dafe26da594954f\\\\\\\",\\\\\\\"maxFeePerGas\\\\\\\":\\\\\\\"0xb2d05e1d\\\\\\\",\\\\\\\"maxPriorityFeePerGas\\\\\\\":\\\\\\\"0xb2d05dcf\\\\\\\",\\\\\\\"nonce\\\\\\\":\\\\\\\"0x1ee\\\\\\\",\\\\\\\"r\\\\\\\":\\\\\\\"0x808bf13e38dde1c5419fc1b5fbabf17e5e6a20ab6212617d6d9a51d219043bf8\\\\\\\",\\\\\\\"s\\\\\\\":\\\\\\\"0x396593e44656b19c74cf01b9a91e88ca1231433bf67975b471e29d0ad5317fb1\\\\\\\",\\\\\\\"to\\\\\\\":\\\\\\\"0x88fd8759c83786b1e11a4b6a6ae15414252827e0\\\\\\\",\\\\\\\"transactionIndex\\\\\\\":\\\\\\\"0x1\\\\\\\",\\\\\\\"type\\\\\\\":\\\\\\\"0x2\\\\\\\",\\\\\\\"v\\\\\\\":\\\\\\\"0x0\\\\\\\",\\\\\\\"value\\\\\\\":\\\\\\\"0x0\\\\\\\"}],\\\\\\\"transactionsRoot\\\\\\\":\\\\\\\"0x8b37e49b0f7eb3445985b1d4619b1265d0a8ea39f7b925b15f8d04eda33a2689\\\\\\\",\\\\\\\"uncles\\\\\\\":[]}\\\" })\"}}", error={"code":-32603}, requestBody="{\"method\":\"eth_getBlockByNumber\",\"params\":[\"latest\",false],\"id\":49,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://127.0.0.1:8545", code=SERVER_ERROR, version=web/5.7.1)
      at Logger.makeError (/home/daniel/code/synthetix-v3/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
      at Logger.throwError (/home/daniel/code/synthetix-v3/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
      at /home/daniel/code/synthetix-v3/node_modules/@ethersproject/web/src.ts/index.ts:341:28
      at step (/home/daniel/code/synthetix-v3/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/home/daniel/code/synthetix-v3/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/home/daniel/code/synthetix-v3/node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:95:5
```

when I remove the forked network deployment option from my tool, deployment works as expected with no error, so I believe this is some sort of a spec issue with anvil.

**Comment by mattsse** [comment]
> missing field `v`

looks like the `v` field of tx is missing when requesting a full block? could you please check?

**Comment by dbeal-eth** [comment]
@mattsse  I apologize. I should have provided more detailed reproduction instructions. Please use the following below instructions to reproduce the error:

1. Run `anvil --fork-url https://goerli.optimism.io/`
2. In another terminal, run `curl --data '{"jsonrpc":"2.0","method": "eth_getBlockByNumber", "params":["latest",false], "id":1}' -H "Content-Type: application/json" http://localhost:8545`. As you can see I am just running `eth_getBlockByNumber`, shouldn't be a problematic call (try running it on mainnet)!

3. Get error
```
➜  ~ curl --data '{"jsonrpc":"2.0","method": "eth_getBlockByNumber", "params":["latest",false], "id":1}' -H "Content-Type: application/json" http://localhost:8545
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Fork Error: JsonRpcClientError(SerdeJson { err: Error(\"missing field `v`\", line: 1, column: 2197), text: \"{\\\"baseFeePerGas\\\":\\\"0x31\\\",\\\"difficulty\\\":\\\"0x0\\\",\\\"extraData\\\":\\\"0x\\\",\\\"gasLimit\\\":\\\"0x17d7840\\\",\\\"gasUsed\\\":\\\"0x0\\\",\\\"hash\\\":\\\"0xd9994194f532633d3da9590ed06ecd9d00ddf33b80d0510648a370844e7b699e\\\",\\\"logsBloom\\\":\\\"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\\\",\\\"miner\\\":\\\"0x4200000000000000000000000000000000000011\\\",\\\"mixHash\\\":\\\"0x14e3841946dabe002df5411b8e2a01ed8a7ceb8e245f99c7e78bdc00014896aa\\\",\\\"nonce\\\":\\\"0x0000000000000000\\\",\\\"number\\\":\\\"0x3f9fe0\\\",\\\"parentHash\\\":\\\"0xad12872dc42abed21bf7d8f7c08ad74875b380dd9130e4c063661cbe521054be\\\",\\\"receiptsRoot\\\":\\\"0x3fd774ff8fe515813d7a8f9d3748e58e857bc002823a458a93be90a3bc2e0894\\\",\\\"sha3Uncles\\\":\\\"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347\\\",\\\"size\\\":\\\"0x364\\\",\\\"stateRoot\\\":\\\"0xd662b1dd1ac83785480e944c4884265b7a967b7e60199b66e36bb624ce49f895\\\",\\\"timestamp\\\":\\\"0x63c3aa24\\\",\\\"totalDifficulty\\\":\\\"0x0\\\",\\\"transactions\\\":[{\\\"blockHash\\\":\\\"0xd9994194f532633d3da9590ed06ecd9d00ddf33b80d0510648a370844e7b699e\\\",\\\"blockNumber\\\":\\\"0x3f9fe0\\\",\\\"from\\\":\\\"0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001\\\",\\\"gas\\\":\\\"0x8f0d180\\\",\\\"hash\\\":\\\"0x1d3e150ca62bd71a058e617750bc213d59b3f08e969fed913228465d8ca84c93\\\",\\\"input\\\":\\\"0x015d8eb900000000000000000000000000000000000000000000000000000000007ede0b0000000000000000000000000000000000000000000000000000000063c3aa04000000000000000000000000000000000000000000000000000000000000000a6584c306e51e9bf8f2990d19ee0b57a26d8b3eebb26b1c2d137b4518696c276600000000000000000000000000000000000000000000000000000000000000020000000000000000000000007431310e026b69bfc676c0013e12a1a11411eec9000000000000000000000000000000000000000000000000000000000000083400000000000000000000000000000000000000000000000000000000000f4240\\\",\\\"nonce\\\":\\\"0x0\\\",\\\"to\\\":\\\"0x4200000000000000000000000000000000000015\\\",\\\"transactionIndex\\\":\\\"0x0\\\",\\\"type\\\":\\\"0x7e\\\",\\\"value\\\":\\\"0x0\\\"}],\\\"transactionsRoot\\\":\\\"0xfe1d1ca0a544327fc851df7d5ccadb64ef3546778488ef82efde93b30de2f3ed\\\",\\\"uncles\\\":[]}\" })"}}
```

**Comment by mattsse** [comment]
the transaction object of the request is missing some parts:

```
 curl --data '{"jsonrpc":"2.0","method": "eth_getBlockByNumber", "params":["latest",true], "id":1}' -H "Content-Type: application/json" https://goerli.optimism.io/ | jq
```

hence the `missing field v` error

**Comment by dbeal-eth** [comment]
> the transaction object of the request is missing some parts:
> 
> ```
>  curl --data '{"jsonrpc":"2.0","method": "eth_getBlockByNumber", "params":["latest",true], "id":1}' -H "Content-Type: application/json" https://goerli.optimism.io/ | jq
> ```
> 
> hence the `missing field v` error

when I run the same command in my terminal I get no error, but only if i replace `https://goerli.optimism.io/` in the above call with `http://localhost:8545`, I get the error. what do you mean "hence the `missing field v` error"?

**Comment by tynes** [comment]
The problem here is the special deposit transaction type, see [here](https://github.com/ethereum-optimism/optimism/blob/develop/specs/deposits.md#the-deposited-transaction-type) for its spec. I suppose we will need to implement that tx type in `ethers-rs`, another problem is that there is a diff to the state transition function for handling L1 to L2 txs (they never revert their value change) as well as the fee payment logic

**Comment by mattsse** [comment]
oh, TIL

@gakonst this would require changes for the ethers `Transaction` rpc type (no signature info)

**Comment by gakonst** [comment]
Can we add an `other: HashMap<String, Value>` type as catch-all, similar to the Arbitrum types?

**Comment by mattsse** [comment]
we already have `OtherFields`:

https://github.com/gakonst/ethers-rs/blob/eaaa01a7d6d7da93fa359dc5113c545d37442dcf/ethers-core/src/types/transaction/response.rs#L121

but this new `Transaction` type lacks signature fields which are mandatory which is causing the error `missing field v`

https://github.com/gakonst/ethers-rs/blob/eaaa01a7d6d7da93fa359dc5113c545d37442dcf/ethers-core/src/types/transaction/response.rs#L58-L67

**Comment by gakonst** [comment]
Let's make them `#[serde(default)]` if they're missing? I _really_ don't want to make it an `Option`.

**Comment by mattsse** [comment]
that should work

**Comment by klkvr** [comment]
Closing as most of the Optimism compatibility issues have been solved after alloy migration
