### ISSUE TITLE
Nonce too low for eth_sendRawTransaction on forked chain

### ISSUE THREAD

**Issue by 0x366** [foundry-rs/foundry#4173]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f959af5 2023-01-06T12:08:29.957131271Z)

### What command(s) is the bug in?

eth_sendRawTransaction

### Operating System

Linux

### Describe the bug

Im trying to send a tx on a forked chain on a past block number.

- My last tx a has nonce = 67

- I do anvil reset to a block in the past
```
Request: {"id":1,"jsonrpc":"2.0","method":"hardhat_reset","params":[{"forking":{"blockNumber":7540398,"jsonRpcUrl":"https://eth-goerli.alchemyapi.io/v2/..."}}]}
Response: {"jsonrpc":"2.0","id":1,"result":null}
```

- Get number of txs -> 60
```
Request: {"id":1,"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["my address","latest"]}
Response: {"jsonrpc":"2.0","id":1,"result":"0x3c"}
```

- Submit tx with nonce = 60
```
Request: {"id":1,"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["<tx body>"]}
Response: {"jsonrpc":"2.0","id":1,"error":{"code":-32003,"message":"nonce too low"}}
```

- Submit same tx, but with nonce = 68
```
Request: {"id":1,"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["<tx body>"]}
Response: {"jsonrpc":"2.0","id":1,"result":"tx hash"}
```

So even tho `eth_getTransactionCount` returns correct results, the `eth_sendRawTransaction` still thinks the nonce should be equal to the latest one.

**Comment by mattsse** [comment]
there was a recent fix related to fork reset https://github.com/foundry-rs/foundry/pull/4140

could you please check if this is still an issue?

**Comment by kvnkmth** [comment]
getting this too. any fix yet?

**Comment by xenide** [comment]
this seems to happen when we have made some changes and then saved it and retrieved it in a new anvil instance using `--state`. The changes made (contracts deployed) are there but somehow the nonce is not updated, as if the changes never happened. 

When we query the nonce using `cast nonce` it indeed shows the old nonce

**Comment by mattsse** [comment]
are these the standard dev accounts?

**Comment by xenide** [comment]
> this happens with the default dev accounts?

yes for mine, I'm using the first (of 10) listed (index 0) when you start anvil

**Comment by mattsse** [comment]
> > this happens with the default dev accounts?
> 
> yes for mine, I'm using the first (of 10) listed (index 0) when you start anvil

mind sharing the logs as described above?

**Comment by xenide** [comment]
> 

You mean just the anvil logs with the following type of info? 
```
    Transaction: 0xd3726f013a3c9958d999c93223c0c07ecd6cc8ae91472c8ad209dbe54c8cade4
    Gas used: 138473

    Block Number: 26788911
    Block Hash: 0x80d4d5f1d294ddd4b063965ab7f1c3c04704c96884c5017ee6efcbe2bf199f81
    Block Time: "Mon, 27 Feb 2023 06:00:58 +0000"
eth_getTransactionReceipt
eth_blockNumber
eth_call
eth_call
``` 

or with even more detailed rust traces?

**Comment by gakonst** [comment]
Was this fixed in #4432?

**Comment by xenide** [comment]
I just tried with the saving the state and restoring via `--state`, it seems that the nonce is not updated

**Comment by mattsse** [comment]
mind sharing the logs?
ref https://github.com/foundry-rs/foundry/issues/4173#issuecomment-1404764142

**Comment by colthreepv** [comment]
I also have the same exact issue as the reporter.

anvil log:
```shell
                             _   _
                            (_) | |
      __ _   _ __   __   __  _  | |
     / _` | | '_ \  \ \ / / | | | |
    | (_| | | | | |  \ V /  | | | |
     \__,_| |_| |_|   \_/   |_| |_|

    0.1.0 (df8ab09 2023-03-14T09:59:59.102392673Z)
    https://github.com/foundry-rs/foundry

Available Accounts
==================

(0) "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" (10000 ETH)
(1) "0x70997970C51812dc3A010C7d01b50e0d17dc79C8" (10000 ETH)
(2) "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC" (10000 ETH)
(3) "0x90F79bf6EB2c4f870365E785982E1f101E93b906" (10000 ETH)
(4) "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65" (10000 ETH)
(5) "0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc" (10000 ETH)
(6) "0x976EA74026E726554dB657fA54763abd0C3a0aa9" (10000 ETH)
(7) "0x14dC79964da2C08b23698B3D3cc7Ca32193d9955" (10000 ETH)
(8) "0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f" (10000 ETH)
(9) "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720" (10000 ETH)

Private Keys
==================

(0) 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
(1) 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
(2) 0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
(3) 0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6
(4) 0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a
(5) 0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba
(6) 0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e
(7) 0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356
(8) 0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97
(9) 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6

Wallet
==================
Mnemonic:          test test test test test test test test test test test junk
Derivation path:   m/44'/60'/0'/0/


Base Fee
==================

100000000

Gas Limit
==================

30000000

Genesis Timestamp
==================

1680687976

Fork
==================
Endpoint:       https://arb-mainnet.g.alchemy.com/v2/it4Um4ecMPP87zNShCGV2GhoFJvxulF8
Block number:   69410517
Block hash:     0xf0b0b27581704cd549f72b4dc192ac5fdded62a7d7f6aaff9ad2e968d35a8c94
Chain ID:       42161


Listening on 127.0.0.1:8545
eth_chainId
eth_estimateGas
eth_sendTransaction
eth_getTransactionReceipt

    Transaction: 0x8bc4ec7c6c59999dadf6d6c7a019dd31d3e1410dbf85218207533ad8ef905b8f
    Gas used: 57975

    Block Number: 69410518
    Block Hash: 0xe69af28f698a993d87b2dd1a34a0a26209823a5afd0230cc6a96d7cab7502c68
    Block Time: "Mon, 13 Mar 2023 10:28:51 +0000"

eth_getTransactionByHash
eth_getTransactionReceipt
eth_chainId
eth_estimateGas
eth_sendTransaction

    Transaction: 0x8465daa2d9ec50483df784004a19f150070a77d6a3b95394dbd87363c30b3c3b
    Gas used: 54232

    Block Number: 69410519
    Block Hash: 0x07918d2be456f5ad59bc44e1efd59ea578a2d1bfaf9d7a5b8354c6ef8eaaba53
    Block Time: "Mon, 13 Mar 2023 10:28:55 +0000"

eth_getTransactionReceipt
eth_getTransactionCount
```

commands given:
```shell
$ anvil \
  -f https://arb-mainnet.g.alchemy.com/v2/it4Um4ecMPP87zNShCGV2GhoFJvxulF8 \
  --fork-block-number 69410517 \
  --state devnetwork.state

LOCALHOST_RPC="http://localhost:8545"
WALLET0="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
WALLET5="0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc"
WETH_CONTRACT="0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"

$ cast send $WETH_CONTRACT "deposit()" --value 10ether \
  --rpc-url $LOCALHOST_RPC --from $WALLET5
$ cast send $WETH_CONTRACT "transfer(address,uint256)" $WALLET0 10000000000000000000 \
  --rpc-url $LOCALHOST_RPC --from $WALLET5
$ cast nonce $WALLET5
4
# after rebooting anvil
$ cast nonce $WALLET5
2
```

devnetwork.state
```json
{"accounts":{"0x0000000000000000000000000000000000000000":{"nonce":0,"balance":"0x9695a0d3c3c748c","code":"0x","storage":{}},"0x14dc79964da2c08b23698b3d3cc7ca32193d9955":{"nonce":0,"balance":"0x21e19e0c9bab2400000","code":"0x","storage":{}},"0x15d34aaf54267db7d7c367839aaf71a00a2c6a65":{"nonce":1,"balance":"0x21e19e0c9bab2400000","code":"0x","storage":{}},"0x23618e81e3f5cdf7f54c3d65f7fbc0abf5b21e8f":{"nonce":0,"balance":"0x21e19e0c9bab2400000","code":"0x","storage":{}},"0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc":{"nonce":0,"balance":"0x21e19e0c9bab2400000","code":"0x","storage":{}},"0x70997970c51812dc3a010c7d01b50e0d17dc79c8":{"nonce":4,"balance":"0x21e19e0c9bab2400000","code":"0x","storage":{}},"0x82af49447d8a07e3bd95bd0d56f35241523fbab1":{"nonce":1,"balance":"0x36c6e4de8cd9f70b3b58","code":"0x60806040526004361061004e5760003560e01c80633659cfe6146100655780634f1ef286146100985780635c60da1b146101185780638f28397014610149578063f851a4401461017c5761005d565b3661005d5761005b610191565b005b61005b610191565b34801561007157600080fd5b5061005b6004803603602081101561008857600080fd5b50356001600160a01b03166101ab565b61005b600480360360408110156100ae57600080fd5b6001600160a01b0382351691908101906040810160208201356401000000008111156100d957600080fd5b8201836020820111156100eb57600080fd5b8035906020019184600183028401116401000000008311171561010d57600080fd5b5090925090506101e5565b34801561012457600080fd5b5061012d610262565b604080516001600160a01b039092168252519081900360200190f35b34801561015557600080fd5b5061005b6004803603602081101561016c57600080fd5b50356001600160a01b031661029f565b34801561018857600080fd5b5061012d610359565b6101996103b6565b6101a96101a4610416565b61043b565b565b6101b361045f565b6001600160a01b0316336001600160a01b031614156101da576101d581610484565b6101e2565b6101e2610191565b50565b6101ed61045f565b6001600160a01b0316336001600160a01b031614156102555761020f83610484565b61024f8383838080601f01602080910402602001604051908101604052809392919081815260200183838082843760009201919091525061038492505050565b5061025d565b61025d610191565b505050565b600061026c61045f565b6001600160a01b0316336001600160a01b031614156102945761028d610416565b905061029c565b61029c610191565b90565b6102a761045f565b6001600160a01b0316336001600160a01b031614156101da576001600160a01b0381166103055760405162461bcd60e51b815260040180806020018281038252603a8152602001806106f8603a913960400191505060405180910390fd5b7f7e644d79422f17c01e4894b5f4f588d331ebfa28653d42ae832dc59e38c9798f61032e61045f565b604080516001600160a01b03928316815291841660208301528051918290030190a16101d5816104c4565b600061036361045f565b6001600160a01b0316336001600160a01b031614156102945761028d61045f565b60606103a98383604051806060016040528060278152602001610732602791396104e8565b9392505050565b3b151590565b6103be61045f565b6001600160a01b0316336001600160a01b0316141561040e5760405162461bcd60e51b81526004018080602001828103825260428152602001806107b56042913960600191505060405180910390fd5b6101a96101a9565b7f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc5490565b3660008037600080366000845af43d6000803e80801561045a573d6000f35b3d6000fd5b7fb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d61035490565b61048d816105eb565b6040516001600160a01b038216907fbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b90600090a250565b7fb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d610355565b60606104f3846103b0565b61052e5760405162461bcd60e51b815260040180806020018281038252602681526020018061078f6026913960400191505060405180910390fd5b60006060856001600160a01b0316856040518082805190602001908083835b6020831061056c5780518252601f19909201916020918201910161054d565b6001836020036101000a038019825116818451168082178552505050505050905001915050600060405180830381855af49150503d80600081146105cc576040519150601f19603f3d011682016040523d82523d6000602084013e6105d1565b606091505b50915091506105e1828286610653565b9695505050505050565b6105f4816103b0565b61062f5760405162461bcd60e51b81526004018080602001828103825260368152602001806107596036913960400191505060405180910390fd5b7f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc55565b606083156106625750816103a9565b8251156106725782518084602001fd5b8160405162461bcd60e51b81526004018080602001828103825283818151815260200191508051906020019080838360005b838110156106bc5781810151838201526020016106a4565b50505050905090810190601f1680156106e95780820380516001836020036101000a031916815260200191505b509250505060405180910390fdfe5472616e73706172656e745570677261646561626c6550726f78793a206e65772061646d696e20697320746865207a65726f2061646472657373416464726573733a206c6f772d6c6576656c2064656c65676174652063616c6c206661696c65645570677261646561626c6550726f78793a206e657720696d706c656d656e746174696f6e206973206e6f74206120636f6e7472616374416464726573733a2064656c65676174652063616c6c20746f206e6f6e2d636f6e74726163745472616e73706172656e745570677261646561626c6550726f78793a2061646d696e2063616e6e6f742066616c6c6261636b20746f2070726f787920746172676574a26469706673582212206c7d9f9210050a2a3b139e9018b711bee78264b2de59dd83f2d515ee541efbf564736f6c634300060c0033","storage":{"0x35":"0x36c6e4de8cd9f70b3b58","0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc":"0x8b194beae1d3e0788a1a35173978001acdfba668","0x470cd5aef11e79c4c4cc8de7e0f37803c472c96f7ee08d855c65c47bb9f881d4":"0x0","0xb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103":"0xd570ace65c43af47101fc6250fd6fc63d1c22a86","0xf6d04bbe1a75429862aa97cc198c639a5559580c07ae94016a2b25986f2e3abd":"0x8ac7230489e80000"}},"0x8b194beae1d3e0788a1a35173978001acdfba668":{"nonce":1,"balance":"0x5cc2d7ebd2bb74","code":"0x60806040526004361061014f5760003560e01c80637ecebe00116100b6578063b760faf91161006f578063b760faf9146105d7578063c2eeeebd146105fd578063c820f14614610612578063d0e30db014610762578063d505accf1461076a578063dd62ed3e146107c85761015f565b80637ecebe00146104b35780638c2a993e146104e65780638fa74a0e1461051f57806395d89b4114610550578063a457c2d714610565578063a9059cbb1461059e5761015f565b8063313ce56711610108578063313ce567146103085780633644e5151461033357806339509351146103485780634000aea01461038157806370a082311461044757806374f4f5471461047a5761015f565b806306fdde0314610164578063095ea7b3146101ee57806318160ddd1461023b578063205c28781461026257806323b872dd1461029b5780632e1a7d4d146102de5761015f565b3661015f5761015d33610803565b005b600080fd5b34801561017057600080fd5b50610179610810565b6040805160208082528351818301528351919283929083019185019080838360005b838110156101b357818101518382015260200161019b565b50505050905090810190601f1680156101e05780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b3480156101fa57600080fd5b506102276004803603604081101561021157600080fd5b506001600160a01b0381351690602001356108a7565b604080519115158252519081900360200190f35b34801561024757600080fd5b506102506108c4565b60408051918252519081900360200190f35b34801561026e57600080fd5b5061015d6004803603604081101561028557600080fd5b506001600160a01b0381351690602001356108ca565b3480156102a757600080fd5b50610227600480360360608110156102be57600080fd5b506001600160a01b0381358116916020810135909116906040013561096f565b3480156102ea57600080fd5b5061015d6004803603602081101561030157600080fd5b50356109fc565b34801561031457600080fd5b5061031d610a06565b6040805160ff9092168252519081900360200190f35b34801561033f57600080fd5b50610250610a0f565b34801561035457600080fd5b506102276004803603604081101561036b57600080fd5b506001600160a01b038135169060200135610a1e565b34801561038d57600080fd5b50610227600480360360608110156103a457600080fd5b6001600160a01b0382351691602081013591810190606081016040820135600160201b8111156103d357600080fd5b8201836020820111156103e557600080fd5b803590602001918460018302840111600160201b8311171561040657600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600092019190915250929550610a72945050505050565b34801561045357600080fd5b506102506004803603602081101561046a57600080fd5b50356001600160a01b0316610b4d565b34801561048657600080fd5b5061015d6004803603604081101561049d57600080fd5b506001600160a01b038135169060200135610b68565b3480156104bf57600080fd5b50610250600480360360208110156104d657600080fd5b50356001600160a01b0316610c02565b3480156104f257600080fd5b5061015d6004803603604081101561050957600080fd5b506001600160a01b038135169060200135610c29565b34801561052b57600080fd5b50610534610c67565b604080516001600160a01b039092168252519081900360200190f35b34801561055c57600080fd5b50610179610c76565b34801561057157600080fd5b506102276004803603604081101561058857600080fd5b506001600160a01b038135169060200135610cd7565b3480156105aa57600080fd5b50610227600480360360408110156105c157600080fd5b506001600160a01b038135169060200135610d45565b61015d600480360360208110156105ed57600080fd5b50356001600160a01b0316610803565b34801561060957600080fd5b50610534610d59565b34801561061e57600080fd5b5061015d600480360360a081101561063557600080fd5b810190602081018135600160201b81111561064f57600080fd5b82018360208201111561066157600080fd5b803590602001918460018302840111600160201b8311171561068257600080fd5b91908080601f0160208091040260200160405190810160405280939291908181526020018383808284376000920191909152509295949360208101935035915050600160201b8111156106d457600080fd5b8201836020820111156106e657600080fd5b803590602001918460018302840111600160201b8311171561070757600080fd5b91908080601f0160208091040260200160405190810160405280939291908181526020018383808284376000920191909152509295505060ff8335169350506001600160a01b03602083013581169260400135169050610d68565b61015d610d7c565b34801561077657600080fd5b5061015d600480360360e081101561078d57600080fd5b506001600160a01b03813581169160208101359091169060408101359060608101359060ff6080820135169060a08101359060c00135610d87565b3480156107d457600080fd5b50610250600480360360408110156107eb57600080fd5b506001600160a01b0381358116916020013516610f1f565b61080d8134610f4a565b50565b60368054604080516020601f600260001961010060018816150201909516949094049384018190048102820181019092528281526060939092909183018282801561089c5780601f106108715761010080835404028352916020019161089c565b820191906000526020600020905b81548152906001019060200180831161087f57829003601f168201915b505050505090505b90565b60006108bb6108b4611036565b848461103a565b50600192915050565b60355490565b6108d43382611126565b6040516000906001600160a01b0384169083908381818185875af1925050503d806000811461091f576040519150601f19603f3d011682016040523d82523d6000602084013e610924565b606091505b505090508061096a576040805162461bcd60e51b815260206004820152600d60248201526c2320a4a62faa2920a729a322a960991b604482015290519081900360640190fd5b505050565b600061097c84848461121c565b6109f284610988611036565b6109ed85604051806060016040528060288152602001612080602891396001600160a01b038a166000908152603460205260408120906109c6611036565b6001600160a01b03168152602081019190915260400160002054919063ffffffff61137316565b61103a565b5060019392505050565b61080d33826108ca565b60385460ff1690565b6000610a1961140a565b905090565b60006108bb610a2b611036565b846109ed8560346000610a3c611036565b6001600160a01b03908116825260208083019390935260409182016000908120918c16815292529020549063ffffffff61143d16565b6000610a7e8484610d45565b50836001600160a01b0316336001600160a01b03167fe19260aff97b920c7df27010903aeb9c8d2be5d310a2c67824cf3f15396e4c1685856040518083815260200180602001828103825283818151815260200191508051906020019080838360005b83811015610af9578181015183820152602001610ae1565b50505050905090810190601f168015610b265780820380516001836020036101000a031916815260200191505b50935050505060405180910390a3610b3d8461149e565b156109f2576109f28484846114a4565b6001600160a01b031660009081526033602052604090205490565b60cc546001600160a01b03163314610bb6576040805162461bcd60e51b815260206004820152600c60248201526b4f4e4c595f4741544557415960a01b604482015290519081900360640190fd5b610bc08282611126565b604051600090339083908381818185875af1925050503d806000811461091f576040519150601f19603f3d011682016040523d82523d6000602084013e610924565b6001600160a01b0381166000908152609960205260408120610c239061157e565b92915050565b6040805162461bcd60e51b815260206004820152600e60248201526d1393d7d094925111d157d352539560921b604482015290519081900360640190fd5b60cc546001600160a01b031681565b60378054604080516020601f600260001961010060018816150201909516949094049384018190048102820181019092528281526060939092909183018282801561089c5780601f106108715761010080835404028352916020019161089c565b60006108bb610ce4611036565b846109ed856040518060600160405280602581526020016121326025913960346000610d0e611036565b6001600160a01b03908116825260208083019390935260409182016000908120918d1681529252902054919063ffffffff61137316565b60006108bb610d52611036565b848461121c565b60cd546001600160a01b031681565b610d758585858585611582565b5050505050565b610d8533610803565b565b83421115610ddc576040805162461bcd60e51b815260206004820152601d60248201527f45524332305065726d69743a206578706972656420646561646c696e65000000604482015290519081900360640190fd5b6000609a54888888610e11609960008e6001600160a01b03166001600160a01b0316815260200190815260200160002061157e565b604080516020808201979097526001600160a01b0395861681830152939094166060840152608083019190915260a082015260c08082018990528251808303909101815260e0909101909152805191012090506000610e6f82611657565b90506000610e7f828787876116a3565b9050896001600160a01b0316816001600160a01b031614610ee7576040805162461bcd60e51b815260206004820152601e60248201527f45524332305065726d69743a20696e76616c6964207369676e61747572650000604482015290519081900360640190fd5b6001600160a01b038a166000908152609960205260409020610f089061180e565b610f138a8a8a61103a565b50505050505050505050565b6001600160a01b03918216600090815260346020908152604080832093909416825291909152205490565b6001600160a01b038216610fa5576040805162461bcd60e51b815260206004820152601f60248201527f45524332303a206d696e7420746f20746865207a65726f206164647265737300604482015290519081900360640190fd5b610fb16000838361096a565b603554610fc4908263ffffffff61143d16565b6035556001600160a01b038216600090815260336020526040902054610ff0908263ffffffff61143d16565b6001600160a01b03831660008181526033602090815260408083209490945583518581529351929391926000805160206120a88339815191529281900390910190a35050565b3390565b6001600160a01b03831661107f5760405162461bcd60e51b815260040180806020018281038252602481526020018061210e6024913960400191505060405180910390fd5b6001600160a01b0382166110c45760405162461bcd60e51b8152600401808060200182810382526022815260200180611f226022913960400191505060405180910390fd5b6001600160a01b03808416600081815260346020908152604080832094871680845294825291829020859055815185815291517f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b9259281900390910190a3505050565b6001600160a01b03821661116b5760405162461bcd60e51b81526004018080602001828103825260218152602001806120c86021913960400191505060405180910390fd5b6111778260008361096a565b6111ba81604051806060016040528060228152602001611f00602291396001600160a01b038516600090815260336020526040902054919063ffffffff61137316565b6001600160a01b0383166000908152603360205260409020556035546111e6908263ffffffff61181716565b6035556040805182815290516000916001600160a01b038516916000805160206120a88339815191529181900360200190a35050565b6001600160a01b0383166112615760405162461bcd60e51b81526004018080602001828103825260258152602001806120e96025913960400191505060405180910390fd5b6001600160a01b0382166112a65760405162461bcd60e51b8152600401808060200182810382526023815260200180611edd6023913960400191505060405180910390fd5b6112b183838361096a565b6112f481604051806060016040528060268152602001611f44602691396001600160a01b038616600090815260336020526040902054919063ffffffff61137316565b6001600160a01b038085166000908152603360205260408082209390935590841681522054611329908263ffffffff61143d16565b6001600160a01b0380841660008181526033602090815260409182902094909455805185815290519193928716926000805160206120a883398151915292918290030190a3505050565b600081848411156114025760405162461bcd60e51b81526004018080602001828103825283818151815260200191508051906020019080838360005b838110156113c75781810151838201526020016113af565b50505050905090810190601f1680156113f45780820380516001836020036101000a031916815260200191505b509250505060405180910390fd5b505050900390565b6000610a19604051808061202e6052913960520190506040518091039020611430611874565b61143861187a565b611880565b600082820183811015611497576040805162461bcd60e51b815260206004820152601b60248201527f536166654d6174683a206164646974696f6e206f766572666c6f770000000000604482015290519081900360640190fd5b9392505050565b3b151590565b604051635260769b60e11b815233600482018181526024830185905260606044840190815284516064850152845187946001600160a01b0386169463a4c0ed369490938993899360840190602085019080838360005b838110156115125781810151838201526020016114fa565b50505050905090810190601f16801561153f5780820380516001836020036101000a031916815260200191505b50945050505050600060405180830381600087803b15801561156057600080fd5b505af1158015611574573d6000803e3d6000fd5b5050505050505050565b5490565b6001600160a01b0382166115cf576040805162461bcd60e51b815260206004820152600f60248201526e494e56414c49445f4741544557415960881b604482015290519081900360640190fd5b60cc546001600160a01b03161561161c576040805162461bcd60e51b815260206004820152600c60248201526b1053149150511657d253925560a21b604482015290519081900360640190fd5b60cc80546001600160a01b038085166001600160a01b03199283161790925560cd805492841692909116919091179055610d758585856118d6565b600061166161140a565b82604051602001808061190160f01b81525060020183815260200182815260200192505050604051602081830303815290604052805190602001209050919050565b60006fa2a8918ca85bafe22016d0b997e4df60600160ff1b038211156116fa5760405162461bcd60e51b8152600401808060200182810382526022815260200180611f6a6022913960400191505060405180910390fd5b8360ff16601b148061170f57508360ff16601c145b61174a5760405162461bcd60e51b815260040180806020018281038252602281526020018061200c6022913960400191505060405180910390fd5b604080516000808252602080830180855289905260ff88168385015260608301879052608083018690529251909260019260a080820193601f1981019281900390910190855afa1580156117a2573d6000803e3d6000fd5b5050604051601f1901519150506001600160a01b038116611805576040805162461bcd60e51b815260206004820152601860248201527745434453413a20696e76616c6964207369676e617475726560401b604482015290519081900360640190fd5b95945050505050565b80546001019055565b60008282111561186e576040805162461bcd60e51b815260206004820152601e60248201527f536166654d6174683a207375627472616374696f6e206f766572666c6f770000604482015290519081900360640190fd5b50900390565b60655490565b60665490565b600083838361188d611997565b6040805160208082019690965280820194909452606084019290925260808301523060a0808401919091528151808403909101815260c090920190528051910120949350505050565b600054610100900460ff16806118ef57506118ef61199b565b806118fd575060005460ff16155b6119385760405162461bcd60e51b815260040180806020018281038252602e815260200180611fde602e913960400191505060405180910390fd5b600054610100900460ff16158015611963576000805460ff1961ff0019909116610100171660011790555b61196c846119ac565b6119768484611a83565b61197f82611b38565b8015611991576000805461ff00191690555b50505050565b4690565b60006119a63061149e565b15905090565b600054610100900460ff16806119c557506119c561199b565b806119d3575060005460ff16155b611a0e5760405162461bcd60e51b815260040180806020018281038252602e815260200180611fde602e913960400191505060405180910390fd5b600054610100900460ff16158015611a39576000805460ff1961ff0019909116610100171660011790555b611a41611b4e565b611a6482604051806040016040528060018152602001603160f81b815250611bef565b611a6d82611caf565b8015611a7f576000805461ff00191690555b5050565b600054610100900460ff1680611a9c5750611a9c61199b565b80611aaa575060005460ff16155b611ae55760405162461bcd60e51b815260040180806020018281038252602e815260200180611fde602e913960400191505060405180910390fd5b600054610100900460ff16158015611b10576000805460ff1961ff0019909116610100171660011790555b611b18611b4e565b611b228383611d6c565b801561096a576000805461ff0019169055505050565b6038805460ff191660ff92909216919091179055565b600054610100900460ff1680611b675750611b6761199b565b80611b75575060005460ff16155b611bb05760405162461bcd60e51b815260040180806020018281038252602e815260200180611fde602e913960400191505060405180910390fd5b600054610100900460ff16158015611bdb576000805460ff1961ff0019909116610100171660011790555b801561080d576000805461ff001916905550565b600054610100900460ff1680611c085750611c0861199b565b80611c16575060005460ff16155b611c515760405162461bcd60e51b815260040180806020018281038252602e815260200180611fde602e913960400191505060405180910390fd5b600054610100900460ff16158015611c7c576000805460ff1961ff0019909116610100171660011790555b8251602080850191909120835191840191909120606591909155606655801561096a576000805461ff0019169055505050565b600054610100900460ff1680611cc85750611cc861199b565b80611cd6575060005460ff16155b611d115760405162461bcd60e51b815260040180806020018281038252602e815260200180611fde602e913960400191505060405180910390fd5b600054610100900460ff16158015611d3c576000805460ff1961ff0019909116610100171660011790555b604051806052611f8c8239604051908190036052019020609a55508015611a7f576000805461ff00191690555050565b600054610100900460ff1680611d855750611d8561199b565b80611d93575060005460ff16155b611dce5760405162461bcd60e51b815260040180806020018281038252602e815260200180611fde602e913960400191505060405180910390fd5b600054610100900460ff16158015611df9576000805460ff1961ff0019909116610100171660011790555b8251611e0c906036906020860190611e44565b508151611e20906037906020850190611e44565b506038805460ff19166012179055801561096a576000805461ff0019169055505050565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f10611e8557805160ff1916838001178555611eb2565b82800160010185558215611eb2579182015b82811115611eb2578251825591602001919060010190611e97565b50611ebe929150611ec2565b5090565b6108a491905b80821115611ebe5760008155600101611ec856fe45524332303a207472616e7366657220746f20746865207a65726f206164647265737345524332303a206275726e20616d6f756e7420657863656564732062616c616e636545524332303a20617070726f766520746f20746865207a65726f206164647265737345524332303a207472616e7366657220616d6f756e7420657863656564732062616c616e636545434453413a20696e76616c6964207369676e6174757265202773272076616c75655065726d69742861646472657373206f776e65722c61646472657373207370656e6465722c75696e743235362076616c75652c75696e74323536206e6f6e63652c75696e7432353620646561646c696e6529496e697469616c697a61626c653a20636f6e747261637420697320616c726561647920696e697469616c697a656445434453413a20696e76616c6964207369676e6174757265202776272076616c7565454950373132446f6d61696e28737472696e67206e616d652c737472696e672076657273696f6e2c75696e7432353620636861696e49642c6164647265737320766572696679696e67436f6e74726163742945524332303a207472616e7366657220616d6f756e74206578636565647320616c6c6f77616e6365ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef45524332303a206275726e2066726f6d20746865207a65726f206164647265737345524332303a207472616e736665722066726f6d20746865207a65726f206164647265737345524332303a20617070726f76652066726f6d20746865207a65726f206164647265737345524332303a2064656372656173656420616c6c6f77616e63652062656c6f77207a65726fa2646970667358221220f7d71875acd75ae506d685741340eef0a3b2b6978b8b20fe57ff92b17488689d64736f6c634300060b0033","storage":{}},"0x90f79bf6eb2c4f870365e785982e1f101e93b906":{"nonce":1,"balance":"0x21e19e0c9bab2400000","code":"0x","storage":{}},"0x976ea74026e726554db657fa54763abd0c3a0aa9":{"nonce":0,"balance":"0x21e19e0c9bab2400000","code":"0x","storage":{}},"0x9965507d1a55bcc2695c58ba16fb37d819b0a4dc":{"nonce":4,"balance":"0x21d8f19384514198080","code":"0x","storage":{}},"0xa0ee7a142d267c1f36714e4a8f75612f20a79720":{"nonce":0,"balance":"0x21e19e0c9bab2400000","code":"0x","storage":{}},"0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266":{"nonce":38,"balance":"0x21e19e0c9bab2400000","code":"0x","storage":{}}}}
```

**Comment by dlarchikov** [comment]
Same problem
```
ProviderError: nonce too low: address 0x000000000000000000, tx: 2 state: 3
    at HttpProvider.request (/Users/dl/Projects/marsContracts/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HardhatEthersSigner.sendTransaction (/Users/dl/Projects/marsContracts/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (/Users/dl/Projects/marsContracts/node_modules/ethers/src.ts/contract/contract.ts:291:20)
    at async Proxy.setImplementation (/Users/dl/Projects/marsContracts/node_modules/ethers/src.ts/contract/contract.ts:330:16)
    at async main (/Users/dl/Projects/marsContracts/scripts/margex-address.ts:17:13)

```

But tx is successful.

**Comment by Nov1kov** [comment]
I have the same error, when I started using `anvil_reset` method instead new instance of anvil in my unit tests. It is slightly similar to the https://github.com/foundry-rs/foundry/issues/1626.
Workaround for me - use a separate de account for each test.

**Comment by iirekm** [comment]
why is this closed as completed? I still have it in forked chain? How to workaround it?
