### ISSUE TITLE
anvil_metadata returning hex instead of ints

### ISSUE THREAD

**Issue by blakearnold** [foundry-rs/foundry#6335]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8c11482 2023-11-16T00:19:25.572835444Z)

### Operating System

macOS (Intel)

### Describe the bug

`anvil_metadata` was recently added https://github.com/foundry-rs/foundry/issues/6221!
But it's returning a hex for the chainID and block numbers instead of an integer.

I called both anvil and hardhat using curl and pasted the result below
` curl -H "Content-Type: application/json" --data "{\"jsonrpc\":\"2.0\",\"method\":\"hardhat_metadata\",\"params\":[],\"id\":67}" http://localhost:8545`

Response from anvil (beautified):
```
{
  "jsonrpc": "2.0",
  "id": 67,
  "result": {
    "clientVersion": "anvil/v0.2.0",
    "chainId": "0xa4b1",
    "instanceId": "0xe9ec6774ec11c9fc287e8f6b6b9a632b0dacfbc33c9995a674ee4971f6eb6f95",
    "latestBlockNumber": "0x86ecb26",
    "latestBlockHash": "0x86a5634f8b594132f00ab9148fa31a0e470d5123e19f57637c9f8cfa2fb7976d",
    "forkedNetwork": {
      "chainId": "0xa4b1",
      "forkBlockNumber": "0x86ecb04",
      "forkBlockHash": "0x58d5e44778a64c817dacf229725568cc279b92996870d762ba07051240fa23c5"
    }
  }
}
```

Result from hardhat (beautified):
```
{
  "jsonrpc": "2.0",
  "id": 67,
  "result": {
    "clientVersion": "HardhatNetwork/2.17.4/@nomicfoundation/ethereumjs-vm/7.0.2",
    "chainId": 42161,
    "instanceId": "0x4d4e724c44b1bbbbf991037eb5da52dc211bac47ed1e29707f66adedb61303ef",
    "latestBlockNumber": 18372607,
    "latestBlockHash": "0x332c4ef08a4ab70b7fb596102c88ae92a84ea327fdd71120deff15a55027c31b",
    "forkedNetwork": {
      "chainId": 1,
      "forkBlockNumber": 18372607,
      "forkBlockHash": "0x332c4ef08a4ab70b7fb596102c88ae92a84ea327fdd71120deff15a55027c31b"
    }
  }
}
```

This is breaking openzeppelin upgrade-core script.

```
Error: Broken invariant: Hardhat metadata's chainId 0xa4b1 does not match eth_chainId 42161
    at getDevInstanceMetadata (/app/contracts/node_modules/@openzeppelin/upgrades-core/src/manifest.ts:60:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.forNetwork (/app/contracts/node_modules/@openzeppelin/upgrades-core/src/manifest.ts:102:33)
```

**Comment by blakearnold** [comment]
Thanks for the quick turnaround! But I couldn't verify this actually fixed it, still seeing the hex being returned:

```
> curl -H "Content-Type: application/json" --data "{\"jsonrpc\":\"2.0\",\"method\":\"hardhat_metadata\",\"params\":[],\"id\":67}" http://localhost:8545

{"jsonrpc":"2.0","id":67,"result":{"clientVersion":"anvil/v0.2.0","chainId":"0xa86a","instanceId":"0xd76a6431c40b910174bc294c4ce48e3d222fddb390131239585cb970c5f5ba63","latestBlockNumber":"0x2fd0927","latestBlockHash":"0x80603f199fbfd09c92ba1b4bec0a89b8da3270751a23079af1fa7821fa13b12f","forkedNetwork":{"chainId":"0xa86a","forkBlockNumber":"0x2fd0927","forkBlockHash":"0x80603f199fbfd09c92ba1b4bec0a89b8da3270751a23079af1fa7821fa13b12f"}}}
```

**Comment by DaniPopes** [comment]
Technically `chainId` and `block.number` are hex encoded in JSON RPC, so both should be checked for and parsed.
